config/routes.rb
Rails.application.routes.draw do
  resources :movie_requests, only: [:new, :create, :show]
  get '/movie_requests', to: redirect('movie_requests/new')
  get '/', to: redirect('movie_requests/new')
end

app/models/movie_request.rb
class MovieRequest < ActiveRecord::Base
	validates_presence_of :title, :year, :poster
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movie_requests_controller.rb
class MovieRequestsController < ApplicationController
  before_action :set_movie_request, only: [:show]

  # GET /movie_requests/1
  def show
  end

  # GET /movie_requests/new
  def new
    @movie_request = MovieRequest.new
  end

  # POST /movie_requests
  def create
    # check if same request already made
    if movie = MovieRequest.find_by(movie_request_params)
      @movie_request = movie
    else
      @movie_request = MovieRequest.new(movie_request_params)
      get_poster(@movie_request)
    end

    if @movie_request.errors.empty? && @movie_request.save
      render 'show'
    else
      render 'new'
    end
  end

  private
    def set_movie_request
      @movie_request = MovieRequest.find(params[:id])
    end

    def movie_request_params
      params.require(:movie_request).permit(:title, :year)
    end

    def get_poster(movie_request)
      movie_response = HttpHelper.get(title: movie_request.title, year: movie_request.year)

      movie_request.errors.add :poster, 'could not be found' if error?(movie_response)
      @movie_request.poster = movie_response['poster']
    end

    # response body has an 'errorcode' attribute if error
    def error?(response)
      response.key?('errorcode')
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/http_helper.rb
require 'http'

module HttpHelper

	HEADERS = {
		"X-Mashape-Key" => "zquo6fAcNNmshkZMlBXDH8KvuR4Ip1mytvojsnGA8wYvSGLN8G",
		"Accept" => "application/json"
	}

	BASE_URL = 'https://community-netflix-roulette.p.mashape.com/api.php?'

	def self.get(params)
		# call get to Mashape API with params as query parameters
		url = "#{BASE_URL}#{format_params(params)}"
		response = HTTP.headers(HEADERS).get(url)

		JSON.parse(response.to_s)
	end

	private

	def self.format_params(params)
		query_parts = params.keys.map do |key|
			no_space = params[key].gsub(' ', '+')
			URI.escape("#{key}=#{no_space}")
		end

		query_parts.join('&')
	end

end

app/helpers/movie_requests_helper.rb
module MovieRequestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Movie Posters</title>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movie_requests/_form.html.erb
<%= form_for(@movie_request) do |f| %>
  <% if @movie_request.errors.any? %>
    <div id="error_explanation">
      <h2>Error</h2>

      <ul>
      <% @movie_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, "Movie Title" %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :year, "Release Year" %><br>
    <%= f.text_field :year %>
  </div>
  <div class="actions">
    <%= f.submit "Get Movie Poster" %>
  </div>
<% end %>

app/views/movie_requests/new.html.erb
<h1>Get A Movie Poster!</h1>

<%= render 'form' %>

app/views/movie_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @movie_request.title %>
</p>

<p>
  <strong>Year:</strong>
  <%= @movie_request.year %>
</p>

<p>
  <%= image_tag(@movie_request.poster) %>
</p>

<%= link_to 'Search Again', new_movie_request_path %>